// -*- C++ -*-
//
// generated by wxGlade 0.7.2 on Thu Oct 20 13:35:21 2016
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef __LABVIEW_H
#define __LABVIEW_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class MainFrame: public wxFrame {
public:
    // begin wxGlade: MainFrame::ids
    // end wxGlade

    MainFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);
	void onQuit(wxCommandEvent& event);
private:
    // begin wxGlade: MainFrame::methods
    void set_properties();
    void do_layout();
	void do_events();

	//void onQuit(wxCommandEvent&);
    // end wxGlade

	int distanceToMove;

	void yUpButtonClicked(wxCommandEvent&);
	void yDownButtonClicked(wxCommandEvent&);
	void xLeftButtonClicked(wxCommandEvent&);
	void xRightButtonClicked(wxCommandEvent&);
	void distanceBoxClicked(wxCommandEvent&);
	void homeButtonClicked(wxCommandEvent&);
	void goToHomeButtonClicked(wxCommandEvent&);
	void goToXHomeButtonClicked(wxCommandEvent&);
	void goToYHomeButtonClicked(wxCommandEvent&);
	int convertDistance(int);

protected:
    // begin wxGlade: MainFrame::attributes
    wxButton* button_8;
    wxButton* up;
    wxButton* button_2;
    wxButton* button_5;
    wxButton* button_4;
    wxButton* button_6;
    wxButton* button_3;
    wxButton* button_7;
    wxComboBox* combo_box_1;
	wxRadioBox* distanceBox;
    // end wxGlade

	wxMenuBar *menubar;
	wxMenu *file;
	wxMenu *edit;
}; // wxGlade: end class


#endif // ..PY_H
