// -*- C++ -*-
//
// generated by wxGlade 0.7.2 on Thu Oct 20 13:35:21 2016
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include "LabView.h"
#include "MotorController.h"
#include "VoltageControlNI.h"

// begin wxGlade: ::extracode
// end wxGlade

const float STEPPERTURN = 400;
const float STEPPERMM = STEPPERTURN/25.4; //TODO change this to be se from within the header dialog

//MotorController mot(6, 9600);
extern MotorController* mot;
extern VoltageNI* volt;

void MainFrame::do_events()
{
	Connect(wxID_EXIT, wxEVT_COMMAND_MENU_SELECTED,
		wxCommandEventHandler(MainFrame::onQuit));
}

void MainFrame::onQuit(wxCommandEvent& WXUNUSED(event))
{
	Close(true);
}

void MainFrame::yUpButtonClicked(wxCommandEvent & event)
{
	//distanceToMove = distanceBox->GetSelection();
	mot->stepMotor(2, distanceToMove);

}

void MainFrame::yDownButtonClicked(wxCommandEvent & event)
{
	//distanceToMove = distanceBox->GetSelection();
	mot->stepMotor(2, -distanceToMove);

}

void MainFrame::xLeftButtonClicked(wxCommandEvent & event)
{
	//distanceToMove = distanceBox->GetSelection();
	mot->stepMotor(1, distanceToMove);

}

void MainFrame::xRightButtonClicked(wxCommandEvent & event)
{
	//distanceToMove = distanceBox->GetSelection();
	mot->stepMotor(1, -distanceToMove);

}

void MainFrame::homeButtonClicked(wxCommandEvent & event)
{
	//distanceToMove = distanceBox->GetSelection();
	mot->setZeroX();
	mot->setZeroY();
}

void MainFrame::goToHomeButtonClicked(wxCommandEvent & event)
{
	//distanceToMove = distanceBox->GetSelection();
	mot->goZero();
}

void MainFrame::distanceBoxClicked(wxCommandEvent & event)
{
	distanceToMove = convertDistance(distanceBox->GetSelection());
}

int MainFrame::convertDistance(int radioButton)
{
	int ret;
	switch (radioButton)
	{
	case 0:
		ret = (int) (0.01 * STEPPERMM);
		break;
	case 1:
		ret = (int)(0.1 * STEPPERMM);
		break;
	case 2:
		ret = (int)(1.0 * STEPPERMM);
		break;
	case 3:
		ret = (int)(5.0 * STEPPERMM);
		break;
	case 4:
		ret = (int)(10.0 * STEPPERMM);
		break;
	default:
		ret = -100;
		break;
	}

	return ret;
}

void MainFrame::scanChooser(wxCommandEvent & event)
{
	static int scanChosen = combo_box_1->GetSelection();

	switch (scanChosen)
	{
	case 0:
		scanType = "Free";
		break;
	case 1:
		scanType = "PixelScan";
		break;
	case 2:
		scanType = "PixelMap";
		break;
	default:
		scanType = "None";
		break;
	}
}
	