// -*- C++ -*-
//
// generated by wxGlade 0.7.2 on Thu Oct 20 13:35:21 2016
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef __LABVIEW_H
#define __LABVIEW_H

#include <wx/wx.h>
#include <wx/image.h>
#include <wx/intl.h>
#include <string>
#include "LabViewVirtual.h"

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade

class BigFrame : public MainFrame
{
public:
	BigFrame(wxWindow* parent );
	void distanceBoxClicked(wxCommandEvent& event);
	int convertDistance(int);
	void onQuit(wxCommandEvent& WXUNUSED(event)); 
	void yUpButtonClicked(wxCommandEvent & event);
	void yDownButtonClicked(wxCommandEvent & event);
	void xLeftButtonClicked(wxCommandEvent & event);
	void xRightButtonClicked(wxCommandEvent & event);
	void homeButtonClicked(wxCommandEvent & event);
	void goToHomeButtonClicked(wxCommandEvent & event);
	void toggleHV(wxCommandEvent& event);
	void setStartVoltage(wxCommandEvent& event);
	void motorControllerConnectClicked(wxCommandEvent & event);
	void motorControllerDisconnectClicked(wxCommandEvent & event);
	void HVConnectClicked(wxCommandEvent & event);
	void BigFrame::openPanelFrame(wxCommandEvent& event);

private:
	int distanceToMove = 400;


};

#endif // ..PY_H
